### ISSUE TITLE
Rapha's Business Intelligence Endpoints

### ISSUE THREAD

**Issue by tgisg** [tgisg/rails_engine#30]
GET /api/v1/merchants/:id/customers_with_pending_invoices
GET /api/v1/merchants/:id/favorite_customer
GET /api/v1/items/most_revenue?quantity=x
GET /api/v1/merchants/revenue?date=x
GET /api/v1/merchants/most_revenue?quantity=x

**Comment by rsbarbo** [comment]
Finished = GET /api/v1/merchants/:id/customers_with_pending_invoices
Finished = GET /api/v1/merchants/:id/favorite_customer

**Comment by rsbarbo** [comment]
Finished = GET /api/v1/items/most_revenue?quantity=x

**Comment by rsbarbo** [comment]
Finished = GET /api/v1/merchants/revenue?date=x
